# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file,
# please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Home
locale: "fi"
author:
  name: Timo Hoo
  email: timo.hoo55.th@gmail.com

description: >- # this means to ignore newlines until "baseurl:"
  Timo Hoon 3D kokeiluja, jotka on
  julkaistu on GitHub Inc -palvelussa.

show_excerpts: false # set to true to show excerpts on the homepage

sass:
    sass_dir: _sass

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%d %b, %Y"
  skin: solarized-dark # classic (default), dark, solarized, solarized-dark

  # generate social links in footer
  social_links:
    twitter: timohoo1
    github:  timohoo
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: ""
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    telegram: ""
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - Villisika.md
  - PhysicsEng.md
  - Puita.md
  - Ukkoja.md
  - Alasiikalampi.md

# Fix into github Authentication error: "GitHub Metadata: No GitHub API authentication could be found."
github: [metadata]

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag

# Outputting
permalink: /:categories/:title/
#paginate: 5 # amount of posts to show
#paginate_path: /page:num/

timezone: Europe/Helsinki # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

defaults:
# _posts

# _pages
#  - scope:
#      path: "_pages"
#      type: default

#archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
